groups:
- name: consumer_alerts
  rules:
  - alert: HighProcessingLatency
    expr: rate(kafka_consumer_processing_seconds_sum[5m]) / rate(kafka_consumer_processing_seconds_count[5m]) > 0.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High message processing latency"
      description: "Average processing time is above 500ms"

  - alert: HighErrorRate
    expr: rate(kafka_consumer_messages_failed_total[5m]) / rate(kafka_consumer_messages_received_total[5m]) > 0.05
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High error rate"
      description: "Error rate is above 5%"
