global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Load all alert rules from the alerts directory
rule_files:
  - "alerts/*.yml"
  - "recording/*.yml"

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093  # Uncomment if you add alert manager later

# Scrape configurations
scrape_configs:
  # Kafka metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 15s

  # Consumer application metrics
  - job_name: 'kafka-consumer'
    static_configs:
      - targets: ['consumer:8000']
    scrape_interval: 15s

  # Node metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
