services:
  # prometheus:
  #   image: prom/prometheus:latest
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #     - ../config/prometheus/alerts/:/etc/prometheus/alerts/:ro
  #     # - prometheus_data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
  #     - '--web.console.templates=/usr/share/prometheus/consoles'
  #   networks:
  #     - kafka-network
  #   healthcheck:
  #     test: ["CMD", "wget", "-q", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # grafana:
  #   image: grafana/grafana:latest
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ../config/grafana/datasources:/etc/grafana/provisioning/datasources:ro
  #     - ../config/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
  #     # - grafana_data:/var/lib/grafana
  #   networks:
  #     - kafka-network
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
  #     - GF_USERS_ALLOW_SIGN_UP=false
  #   healthcheck:
  #     test: ["CMD", "wget", "-q", "--tries=1", "--spider", "http://localhost:3000/api/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - '--kafka.server=kafka:9092'
    ports:
      - "9308:9308"
    networks:
      - kafka-network
    depends_on:
      kafka:
        condition: service_healthy

  node-exporter:
    image: prom/node-exporter:latest
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - kafka-network