datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: true
    tlsSkipVerify: true               # Only if using HTTPS without cert verification
    timeInterval: "5s"                # Optional, sets a minimum query interval
    httpHeaderName1: "Authorization"  # Only if needed for authentication
    httpHeaderValue1: "Bearer YOUR_TOKEN_HERE"
