#!/bin/bash
# Script to check if Kafka is running by attempting a status check.
# This script verifies if Kafka is operational within the Docker Compose setup.
# NOTE: This script is intended for use after Kafka and related services have started.
#       It is not a system pre-check and will only work if services are already running.
# See below for Usage instructions.

# To exit on first error in the script.
set -e

# Usage instructions:
#
# scripts/kafka-status

echo -e "\nKafka Container Status:"
docker ps -a | grep kafka

echo "Checking Kafka services..."

# Display service status for Kafka and Zookeeper
echo "Service Status:"
docker compose -f docker/docker-compose.yml ps

# Display resource usage for Kafka and Zookeeper containers
echo -e "\nResource Usage:"
docker compose -f docker/docker-compose.yml top

kafka_topics=$(scripts/list-topics | grep -v '^[[:space:]]*$' | tr -d '[:space:]')
num_topics=$(echo -n "$kafka_topics" | wc -l)
if [ "$num_topics" -gt 0 ]; then
    echo -e "\nNumber of Kafka Topics: $num_topics"
    echo -e "\nKafka Topics:"
    echo "$kafka_topics"
else
    echo -e "\nNo Kafka topics found."
fi

# Display the last 10 lines of logs for the Kafka data generator
echo -e "\nChecking data generator logs:"
docker compose -f docker/docker-compose.yml logs --tail=10 kafka-data-generator
