#!/bin/bash
set -e

echo "Starting zookeeper detached... "
docker compose -f docker/docker-compose.yml up -d zookeeper 

# Wait for Zookeeper to be fully up and running
./scripts/wait-for-service zookeeper 2181

echo "Starting kafka attached... "
docker compose -f docker/docker-compose.yml up kafka 

# Wait for Kafka to be fully up and running
./scripts/wait-for-service kafka 9092 20 5

echo "Starting producer detached... "
docker compose -f docker/docker-compose.yml up -d producer

# Wait for producer to be fully up and running
./scripts/healthcheck_producer0

# List all containers
docker ps -a
