services:
  kafka-transformer:
    build: .
    environment:
      INSTANCE_ID: 0
      BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_IN: B
      KAFKA_TOPIC_OUT: L
    depends_on:
      - kafka
    networks:
      - kafka-network

  # Only if you're running a local Kafka for testing
  kafka:
    image: wurstmeister/kafka:2.13-2.8.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true